// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5jVjaJ4SsrH8lJRJu_cSmZuRk-_cw-iw',
    appId: '1:387407112502:web:201204103ced78d7c9ab97',
    messagingSenderId: '387407112502',
    projectId: 'intern-project-ff46b',
    authDomain: 'intern-project-ff46b.firebaseapp.com',
    storageBucket: 'intern-project-ff46b.firebasestorage.app',
    measurementId: 'G-P3XWQD4T8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCScdUlbYNGqYic_fjHJt0_5yQzcvaJU',
    appId: '1:387407112502:android:74f5c89c578d5be6c9ab97',
    messagingSenderId: '387407112502',
    projectId: 'intern-project-ff46b',
    storageBucket: 'intern-project-ff46b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCORkd1X6xm1gD-Md1feDiHlS9sAaSjjU',
    appId: '1:387407112502:ios:f7db3095adfba5b8c9ab97',
    messagingSenderId: '387407112502',
    projectId: 'intern-project-ff46b',
    storageBucket: 'intern-project-ff46b.firebasestorage.app',
    iosBundleId: 'com.example.ToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCORkd1X6xm1gD-Md1feDiHlS9sAaSjjU',
    appId: '1:387407112502:ios:f7db3095adfba5b8c9ab97',
    messagingSenderId: '387407112502',
    projectId: 'intern-project-ff46b',
    storageBucket: 'intern-project-ff46b.firebasestorage.app',
    iosBundleId: 'com.example.ToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5jVjaJ4SsrH8lJRJu_cSmZuRk-_cw-iw',
    appId: '1:387407112502:web:fe33750c9c854aa4c9ab97',
    messagingSenderId: '387407112502',
    projectId: 'intern-project-ff46b',
    authDomain: 'intern-project-ff46b.firebaseapp.com',
    storageBucket: 'intern-project-ff46b.firebasestorage.app',
    measurementId: 'G-3K8GK6HMNQ',
  );
}
